# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import aiq_server_pb2 as aiq__server__pb2


class AiqTranslationServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Translate = channel.unary_unary(
        '/AiqTranslationServer/Translate',
        request_serializer=aiq__server__pb2.Translatable.SerializeToString,
        response_deserializer=aiq__server__pb2.Translation.FromString,
        )
    self.SourceLanguage = channel.unary_unary(
        '/AiqTranslationServer/SourceLanguage',
        request_serializer=aiq__server__pb2.Source.SerializeToString,
        response_deserializer=aiq__server__pb2.Language.FromString,
        )


class AiqTranslationServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Translate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SourceLanguage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AiqTranslationServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Translate': grpc.unary_unary_rpc_method_handler(
          servicer.Translate,
          request_deserializer=aiq__server__pb2.Translatable.FromString,
          response_serializer=aiq__server__pb2.Translation.SerializeToString,
      ),
      'SourceLanguage': grpc.unary_unary_rpc_method_handler(
          servicer.SourceLanguage,
          request_deserializer=aiq__server__pb2.Source.FromString,
          response_serializer=aiq__server__pb2.Language.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AiqTranslationServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
